parameters:
    piappgedmo.manager.jquery.flexslider.class: PiApp\GedmoBundle\Util\PiJquery\PiFlexSliderManager

services:
    #
    # configuration of the JQUERY Util classes
    #
    pi_app_gedmo.jquery_manager.flexslider:
        class: %piappgedmo.manager.jquery.flexslider.class%
        arguments: ['@service_container']